### ISSUE TITLE
Todo list v2

### ISSUE THREAD

**Issue by 93ams** [tilau2328/Chat#2]
- [x] acabar a base de dados remota
- [x] criar interface e/ou base de dados local
- [x] implementar rebalanceamento das salas nos servidores
- [ ] por o servidor a servir em json
- [ ] implementar templates
- [ ] implementar ajax
